language: viml
install:
  - sudo apt-get update -q
  - sudo apt-get install vim-nox

before_script:
  - git clone https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 /tmp/vim-themis

script:
  - vim --cmd version --cmd quit
  - /tmp/vim-themis/bin/themis test/ -r --reporter dot

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
