language: viml
sudo:     false

before_script:
  - git clone https://github.com/vim/vim --depth 1 /tmp/vim && cd /tmp/vim && ./configure --with-features=huge && make && make install && cd -
  - git clone https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 /tmp/vim-themis

script:
  - echo $PATH
  - vim --cmd version --cmd quit
  - /tmp/vim-themis/bin/themis test/ -r --reporter dot

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
