language: generic
env:
  - PPA=yes
  - PPA=no

before_install:
  - uname -a
  - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /var/lib/locales/supported.d/local
  - echo ja_JP.UTF-8 UTF-8 | sudo tee -a /etc/locale.gen
  - sudo /usr/sbin/locale-gen

install:
  - if [ x"$PPA" == "xyes" ] ; then sudo add-apt-repository ppa:pi-rho/dev -y; fi
  - sudo apt-get update -q
  - sudo apt-get install vim-nox

before_script:
  - git clone https://github.com/thinca/vim-themis --branch v1.4.1 --single-branch --depth 1 /tmp/vim-themis

script:
  - vim --cmd version --cmd quit
  - /tmp/vim-themis/bin/themis test/ -r --reporter dot

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
